Emp_register1web/Models/EmpRegister.cs
using Microsoft.VisualBasic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Emp_register1web.Models
{
    public class EmpRegister
    {
        [Key]
        public int EmployeeId { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }


        [EmailAddress (ErrorMessage = "invalid Email Address")]
        public string Email { get; set; }

        public string Gender { get; set; }
        [Required(ErrorMessage = "Please Enter Date")]
        [DataType (DataType.Date)]
        public DateTime DateOfJoining { get; set; } 
        [Required]
        public string Department { get; set; }

        [Required]
        public string Location { get; set; }
    }
}

Emp_register1web/Models/ErrorViewModel.cs
namespace Emp_register1web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Emp_register1web/Controllers/EmpRegisterController.cs
using Emp_register1web.Data;
using Emp_register1web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Emp_register1web.Controllers
{
    public class EmpRegisterController : Controller
    {
        private readonly ApplicationDbContext _db;
        public EmpRegisterController(ApplicationDbContext db) 
        {
            _db = db;
        }
		//return view containing a list of all the empregister object in the database 
		public IActionResult Index()
        {
            IEnumerable<EmpRegister> objEmpList = _db.EmpRegister;
            return View(objEmpList);
        }
        

    }
}

Emp_register1web/Controllers/HomeController.cs
using Emp_register1web.Data;
using Emp_register1web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Emp_register1web.Controllers
{
    //Constructor to initialize the logger and the database content 
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly ApplicationDbContext _db;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }
        //Action method to display the home page
        public IActionResult Index()
        {
            return View();
        }
        //Action method to display the empregister page with the list of registerd employees
        public IActionResult Employee()
        {
            IEnumerable<EmpRegister> objEmpList = _db.EmpRegister;
            return View(objEmpList);
        }

        //Action method to form submission to add new employee
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(EmpRegister obj) 
        {
            if (ModelState.IsValid) 
            {
                _db.EmpRegister.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Registered successfully";
                return RedirectToAction("Employee");
            }
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Emp_register1web/Views/EmpRegister/Index.cshtml
@{
    ViewData["Title"] = "Index";
}



<h1>Registered Employee</h1>



<table class="table table-bordered table stripped" style="width:100%">
    <!--Table Header-->
    <thead>
        <tr>
            <th>
                Employee Id
            </th>
            <th>
                Full Name
            </th>
            
            <th>
                Gender
            </th>
            <th>
                Email
            </th>
            <th>
                Date Of Joining
            </th>
            <th>
                Department
            </th>
            <th>
                Location
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td width="8%">
                    @obj.EmployeeId
                </td>
                <td width="15%">
                    @obj.FirstName @obj.LastName
                </td>
                
                <td width="15%">
                    @obj.Gender
                </td>
                <td width="15%">
                    @obj.Email
                </td>
                <td width="15%">
                    @obj.DateOfJoining
                </td>
                <td width="15%">
                    @obj.Department
                </td>
                <td width="20%">
                    @obj.Location
                </td>
                



            </tr>
        }
    </tbody>
</table>

Emp_register1web/Views/Home/Index.cshtml
@model EmpRegister
@{
    ViewData["Title"] = "Index";
}
<h2>Employee Registration</h2>
<br />

<form method="post">
  <div class="row">
        <div class="container" style="border:2px">
            <div class="col-md-4 offset-4 border border-primary rounded pl-5 pr-5 pb-5  justify-content-center pt-5">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">              
                <label asp-for="FirstName" style="margin-bottom:5px; display:inline-block;"> </label>
                <input type="text" asp-for="FirstName" style="margin-left:30px;">
                <br />
                <span asp-validation-for="FirstName" class="text-danger"></span>             
            </div> 
            <br />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">              
                <label  asp-for="LastName" style="margin-bottom:5px; display:inline-block;"> </label>&nbsp;&nbsp;
                <input type="text" asp-for="LastName" style="margin-left:20px;">
                <br />
                <span asp-validation-for="LastName" class="text-danger"></span>            
            </div>
            <br />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">              
                <label asp-for="Email" style="margin-bottom:5px; display:inline-block;"></label>&nbsp;
                <input type="email" asp-for="Email" style="margin-left:55px;">
                <br />
                <span asp-validation-for="Email" class="text-danger"></span>             
            </div>
            <br />
            <div class="form-group">                         
                <label asp-for="Gender" style="margin-bottom:5px; display:inline-block; margin-right:70px; " ></label>
                <input type="radio" asp-for="Gender" id="Male" name="Gender" value="Male" style="margin-left:30px;">
                <label for="Male" style="margin-right:20px; ">Male</label>&nbsp;&nbsp;
                <input type="radio" id="Female" name="Gender" value="Female">
                <label for="Female">Female</label>                                
            </div>
            <br />
            <div class="form-group">               
                <label asp-for="DateOfJoining" style="margin-bottom:5px; display:inline-block;"></label>
                <input type="date" asp-for="DateOfJoining" name="DateOfJoining" id="DateOfJoining" style="margin-left:53px;">
                <br />              
            </div>
            <br />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">               
                <label asp-for="Department" style="margin-bottom:5px; display:inline-block;"></label>
                <Select type="text" name="department" id="department" style="margin-left:17px;">
                <option value="Appliction Development">AI Development</option>
                <option value="System Development">System Development</option>
                <option value="AI Development">Appliction Development</option>
                </Select>              
            </div>
            <br />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">               
                <label asp-for="Location" style="margin-bottom:5px; display:inline-block;"></label>
                <input type="text" asp-for="Location" name="Location" id="Location" style="margin-left:50px;">
                <br />
                <span asp-validation-for="Location" class="text-danger"></span>              
            </div>
            <br />
            <div class="form-group">                           
                <button type="submit" class="btn btn-outline-primary" style="width:150px"> Save</button>&nbsp;&nbsp;
                <button type="reset" onclick="this.form.reset();return false" class="btn btn-outline-primary" style="width:150px">Cancel</button>                                        
            </div>
            </div>
        </div>
   </div>
   

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Emp_register1web/Views/Shared/Employee.cshtml
@{
    ViewData["Title"] = "Index";
}



<h1>Registered Employee</h1>



<table class="table table-bordered table stripped" style="width:100%">
    <!--Table header-->
    <thead>
        <tr>
            <th>
                Employee Id
            </th>
            <th>
                Full Name
            </th>
            
            <th>
                Gender
            </th>
            <th>
                Email
            </th>
            <th>
                Date Of Joining
            </th>
            <th>
                Department
            </th>
            <th>
                Location
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td width="8%">
                    @obj.EmployeeId
                </td>
                <td width="15%">
                    @obj.FirstName @obj.LastName
                </td>
                
                <td width="10%">
                    @obj.Gender
                </td>
                <td width="15%">
                    @obj.Email
                </td>
                <td width="15%">
                    @obj.DateOfJoining.ToString(string.Format("dd/MM/yyyy"))
                </td>
                <td width="15%">
                    @obj.Department
                </td>
                <td width="20%">
                    @obj.Location
                </td>
               
            </tr>
        }
    </tbody>
</table>

Emp_register1web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee Registration</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Emp_register1web.styles.css" asp-append-version="true" />
    <style>
        .container{
            text-align:center;
        }
        
    </style>
    
</head>
<body>
    
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employee Registration</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmpRegister" asp-action="Index">Employee Registration</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Emp_register1web </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>